version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: api-report-nexus
    main: ./cmd/api
    binary: api-report-nexus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

dockers_v2:
  - id: api-report-nexus
  - ids:
      - api-report-nexus
    images:
      - "ghcr.io/blogicsystems/api-report-nexus"
    tags:
      - "{{ .Tag }}"
      - "latest"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
    flags:
      - "--provenance=false"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: blogicsystems
    name: api-report-nexus
  footer: >-

    ---

    Released by [ZenKiet](https://github.com/zenkiet).
